[package]
name = "profile_stack"
version = "0.1.0"
authors = ["Matthew Gleich <email@mattglei.ch>"]
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
anyhow = "1.0.40"
tracing = "0.1"
tracing-subscriber = "0.2.0"
percent-encoding = "2.1.0"
